data:
  template_path: preprocessing_data/faces_colour_template.ply  #face_7_features.ply #faces_colour_template.ply         # vertices should be coloured (vertex semantic segmentation)
  precomputed_path: precomputed
  dataset_type: faces_babies_faces
  dataset_path: /raid/compass/athena/data/DATA_BABIES_FACES
  dataset_metadata_path: preprocessing_data/BABIES_faces_metadata_YEARS.csv
  # template_path: preprocessing_data/face_combined_8_features.ply    # vertices should be coloured (vertex semantic segmentation)
  # precomputed_path: precomputed
  # dataset_type: faces_babies_faces_combined
  # dataset_path: /raid/compass/athena/data/unified_normals_dataset 
  # dataset_metadata_path: preprocessing_data/combined_datasets_ages.csv 
  dataset_remove: []                                                        # remove specific meshes from the dataset
  dataset_age_range: 0-17                                                      # age range that data set is restricted to seperated by a '-'
  normalize_data: True
  to_mm_constant: 87                                                       # if already in mm set to 1, otherwise set proper multiplicative constant
  std_pca_latent: 3                                                             # for data generation, 1 to sample from correct distribution, > 1 exaggerate face shapes
  number_of_meshes: 10000                                                       # for data generation, > 0 if you want to generate data
  number_of_workers: 8
  swap_features: True                                                           # if True, the resulting batch size will be batch_size^2
  
optimization:
  epochs: 600
  batch_size: 4                                                                 # if swap_features=True, the resulting batch size will be batch_size^2
  lr: 1e-4
  weight_decay: 0

  reconstruction_weight: 1
  laplacian_weight: 5   
  kl_weight: 5e-4                                                               # if 0, AE or RAE architecture is used                                  

  gaussian_weight: 0                                                            # alternative to KL divergence
  gaussian_mean_weight: 0

  latent_consistency_weight: 5                                                # if 0, no latent consistency loss is used
  latent_consistency_eta1: 0.5
  latent_consistency_eta2: 0.5

  rae_weight: 0                                                                 # if 0, no Regularized AE (RAE). If > 0 kl, dip, and factor weights must be 0
  rae_embedding: 1e-4
  rae_grad_penalty: 0.5e-7                                                      # If 0, L2 normalization is used and must set rae_gen_weight_decay. Default for GP: 0.5e-7
  rae_gen_weight_decay: 1e-7                                                    # Ignored if rae_grad_penalty > 0
  rae_n_gaussians: 10

  dip_weight: 0                                                                 # if 0, no dip loss is used
  dip_type: i
  dip_diag_lambda: 0.05
  dip_offdiag_lambda: 0.1

  factor_weight: 0                                                              # if 0, no factor VAE

### new age related losses

  age_weight: 1                                                                  # if 0, no age loss is used
  
  contrastive_weight: 0 #1                                                         # if 0, no contrastive loss is used
  contrastive_loss_temp: 100                                                     
  contrastive_loss_threshold: 0.035    

  mi_weight: 0 #1

  adversarial_weight: 1                                           

model:
  sampling:
    type: basic  # r_weighted                                                               # {basic, r_weighted}. Delete precomputed file if changed
    sampling_factors: [4, 2, 2, 2]
  spirals:
    length: [9, 9, 9, 9]                                                        # length of spiral for each convolution. Delete precomputed file if changed.
    dilation: [1, 1, 1, 1]                                                      # spiral dilation for each convolution. Delete precomputed file if changed.
  in_channels: 3                                                                # number of input vertex features. Most likely 3 (x, y, z)
  out_channels: [32, 32, 32, 64]                                                # channels of intermediate layers
  latent_size: 45                                                               # size of the latent vector
  age_per_feature: True                                                        # if True, a single age latent is added per feature. 
  age_latent_size: 9                                                         # size of additional age latents
  pre_z_sigmoid: False
  age_disentanglement: True                                                     # if True, an extra feature is added to the latent vector that represents age & age related losses are added
  contrastive_loss: False #True                                                        # if True, contrastive loss is used
  mi_loss: False #True
  adversarial_loss: True                                                        # if True, adversarial loss is used
  discriminator_type: "MLP" # "Spiral" "MLP"
  intermediate_layers: False                                                    # if True, intermediate layers are used
  intermediate_layers_count: 2                                                 # number of intermediate layers
  intermediate_layers_size: 120                                                 # size of the intermediate layers

logging_frequency:
  tb_renderings: 50
  save_weights: 200

testing:
  age_latent_changing: [0, 0.00, 4.00, 8.00, 12.00, 17.00]                               # first value will always change to what the original latent age value is
